# Generated by Django 5.0.7 on 2025-02-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('normal_user', 'Normal User'), ('admin', 'Admin'), ('pandit', 'Pandit')], default='normal_user', max_length=15),
        ),
        migrations.CreateModel(
            name='Pandit',
            fields=[
                ('pandit_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_years', models.IntegerField()),
                ('experience_description', models.TextField()),
                ('languages_spoken', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registerlogin.user')),
            ],
            options={
                'db_table': 'Pandit',
            },
        ),
    ]
