# Generated by Django 5.0.7 on 2025-02-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerlogin', '0002_alter_user_user_role_pandit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandit',
            name='languages_spoken',
            field=models.JSONField(),
        ),
    ]
