# Generated by Django 5.0.7 on 2025-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerlogin', '0003_alter_pandit_languages_spoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandit',
            name='languages_spoken',
            field=models.TextField(),
        ),
    ]
