# Generated by Django 5.0.7 on 2025-02-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerlogin', '0004_alter_pandit_languages_spoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='languages_spoken',
        ),
    ]
