# Generated by Django 5.0.7 on 2025-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerlogin', '0008_alter_user_user_role_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pandit',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
