# Generated by Django 5.0.7 on 2025-03-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
