# Generated by Django 5.0.7 on 2025-03-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_rentalitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItemSize',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='renting.rentalitem')),
            ],
            options={
                'db_table': 'RentalItemSize',
                'unique_together': {('rental_item', 'size')},
            },
        ),
    ]
