# Generated by Django 5.0.7 on 2025-03-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_rentalitemsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalitem',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='size',
        ),
        migrations.AlterModelTable(
            name='rentalitem',
            table='rental_item',
        ),
        migrations.CreateModel(
            name='ItemSizeVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='renting.rentalitem')),
            ],
            options={
                'db_table': 'item_size_variant',
                'unique_together': {('rental_item', 'size')},
            },
        ),
        migrations.DeleteModel(
            name='RentalItemSize',
        ),
    ]
