# Generated by Django 5.0.7 on 2025-03-16 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='rental_days',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rental_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rental_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
