# Generated by Django 5.0.7 on 2025-03-17 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0006_remove_cartitem_rental_days_cartitem_rental_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=100)),
                ('metro_area', models.CharField(blank=True, max_length=100, null=True)),
                ('area_name', models.CharField(max_length=100)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'delivery_location',
                'unique_together': {('province', 'metro_area', 'area_name')},
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='renting.deliverylocation'),
        ),
    ]
