# Generated by Django 5.0.7 on 2025-03-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0007_alter_cart_options_alter_cart_table_deliverylocation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
