# Generated by Django 5.0.7 on 2025-03-31 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0010_order_khalti_data_order_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('rental_start_date', models.DateField()),
                ('rental_end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='renting.order')),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.rentalitem')),
                ('size_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.itemsizevariant')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
