# Generated by Django 5.0.7 on 2025-04-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0011_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
