# Generated by Django 5.0.7 on 2025-04-07 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0012_deliverylocation_landmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RentalItemReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='renting.rentalitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rental_item_review',
                'ordering': ['-created_at'],
                'unique_together': {('rental_item', 'user')},
            },
        ),
    ]
