# Generated by Django 5.0.7 on 2025-04-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0013_rentalitem_average_rating_rentalitem_total_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='total_reviews',
        ),
        migrations.DeleteModel(
            name='RentalItemReview',
        ),
    ]
