# Generated by Django 5.0.7 on 2025-04-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0014_remove_rentalitem_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='full_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
