# Generated by Django 5.0.7 on 2025-04-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0015_cart_full_location_cart_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_location',
        ),
    ]
