# Generated by Django 5.0.7 on 2025-03-31 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit_booking', '0002_panditreview'),
        ('registerlogin', '0009_pandit_average_rating_pandit_total_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanditAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='registerlogin.pandit')),
            ],
            options={
                'db_table': 'PanditAvailability',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('pandit', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
