# Generated by Django 5.0.7 on 2025-04-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit_booking', '0003_panditavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='panditbooking',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panditbooking',
            name='location_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='panditbooking',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panditbooking',
            name='location_metro_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='panditbooking',
            name='location_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
