# Generated by Django 5.0.7 on 2025-04-08 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit_booking', '0004_panditbooking_landmark_panditbooking_location_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('booking_created', 'New Booking Created'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pandit_booking.panditbooking')),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
