# Generated by Django 5.0.7 on 2025-04-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit_booking', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'New Booking Created'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('new_review', 'New Review Received')], max_length=50),
        ),
    ]
