# Generated by Django 5.0.7 on 2025-04-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0018_ihilocation_ihiregistration'),
        ('pandit_booking', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_event_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='adminwork.eventregistration'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'New Booking Created'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('new_review', 'New Review Received'), ('event_registration_success', 'Event Registration Successful')], max_length=50),
        ),
    ]
