# Generated by Django 5.0.7 on 2025-04-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit_booking', '0007_notification_related_event_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panditbooking',
            name='location_area',
        ),
        migrations.RemoveField(
            model_name='panditbooking',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='panditbooking',
            name='location_metro_area',
        ),
        migrations.RemoveField(
            model_name='panditbooking',
            name='location_province',
        ),
        migrations.AddField(
            model_name='panditbooking',
            name='full_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panditbooking',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panditbooking',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
