# Generated by Django 5.0.7 on 2025-04-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandit_booking', '0008_remove_panditbooking_location_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
