# Generated by Django 5.0.7 on 2025-02-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminwork.category')),
                ('event_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminwork.eventdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventRegistration',
                'unique_together': {('event_detail', 'user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('drinks', models.CharField(blank=True, max_length=200, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminwork.eventregistration')),
            ],
            options={
                'db_table': 'RegistrationDetail',
            },
        ),
    ]
