# Generated by Django 5.0.7 on 2025-02-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0002_category_eventregistration_registrationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BhintunaRally',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'BhintunaRally',
            },
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='rally_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminwork.bhintunarally'),
        ),
    ]
