# Generated by Django 5.0.7 on 2025-03-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0003_bhintunarally_registrationdetail_rally_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhintunarally',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BhintunaRallyLap',
            fields=[
                ('lap_id', models.AutoField(primary_key=True, serialize=False)),
                ('lap_number', models.PositiveIntegerField()),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('rally_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminwork.bhintunarally')),
            ],
            options={
                'db_table': 'BhintunaRallyLap',
                'unique_together': {('rally_option', 'lap_number')},
            },
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='rally_laps',
            field=models.ManyToManyField(blank=True, to='adminwork.bhintunarallylap'),
        ),
    ]
