# Generated by Django 5.0.7 on 2025-03-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0004_bhintunarally_available_seats_bhintunarallylap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhintunarallylap',
            old_name='end_location',
            new_name='route_description',
        ),
        migrations.RemoveField(
            model_name='bhintunarallylap',
            name='start_location',
        ),
    ]
