# Generated by Django 5.0.7 on 2025-03-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0005_rename_end_location_bhintunarallylap_route_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhintunarallylap',
            name='available_seats',
        ),
    ]
