# Generated by Django 5.0.7 on 2025-03-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0006_remove_bhintunarallylap_available_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewariInstrument',
            fields=[
                ('instrument_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'NewariInstrument',
            },
        ),
        migrations.CreateModel(
            name='VolunteerLap',
            fields=[
                ('lap_id', models.AutoField(primary_key=True, serialize=False)),
                ('lap_number', models.PositiveIntegerField()),
                ('route_description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'VolunteerLap',
            },
        ),
        migrations.CreateModel(
            name='VolunteerType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'VolunteerTypes',
                'db_table': 'VolunteerType',
            },
        ),
        migrations.RemoveField(
            model_name='registrationdetail',
            name='music_instrument',
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='newari_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminwork.newariinstrument'),
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='volunteer_laps',
            field=models.ManyToManyField(blank=True, to='adminwork.volunteerlap'),
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='volunteer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminwork.volunteertype'),
        ),
    ]
