# Generated by Django 5.0.7 on 2025-03-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0007_newariinstrument_volunteerlap_volunteertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerlap',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
