# Generated by Django 5.0.7 on 2025-03-17 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0008_volunteerlap_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
    ]
