# Generated by Django 5.0.7 on 2025-03-18 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0009_alter_eventregistration_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'StallTypes',
                'db_table': 'StallType',
            },
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='food_items',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='stall_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminwork.stalltype'),
        ),
    ]
