# Generated by Django 5.0.7 on 2025-03-18 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0010_stalltype_registrationdetail_food_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'StallLocation',
            },
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='stall_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminwork.stalllocation'),
        ),
    ]
