# Generated by Django 5.0.7 on 2025-03-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0011_stalllocation_registrationdetail_stall_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhintunarally',
            name='event_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rally_options', to='adminwork.eventdetail'),
        ),
        migrations.AddField(
            model_name='newariinstrument',
            name='event_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='adminwork.eventdetail'),
        ),
        migrations.AddField(
            model_name='stalllocation',
            name='event_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stall_locations', to='adminwork.eventdetail'),
        ),
        migrations.AddField(
            model_name='stalltype',
            name='event_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stall_types', to='adminwork.eventdetail'),
        ),
        migrations.AddField(
            model_name='volunteerlap',
            name='event_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_laps', to='adminwork.eventdetail'),
        ),
        migrations.AddField(
            model_name='volunteertype',
            name='event_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_types', to='adminwork.eventdetail'),
        ),
    ]
