# Generated by Django 5.0.7 on 2025-03-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0012_bhintunarally_event_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerlap',
            name='lap_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
