# Generated by Django 5.0.7 on 2025-03-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0014_bhintunaticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhintunaticket',
            old_name='price',
            new_name='price_per_seat',
        ),
        migrations.AddField(
            model_name='bhintunaticket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
