# Generated by Django 5.0.7 on 2025-03-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0015_rename_price_bhintunaticket_price_per_seat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhintunaticket',
            old_name='price_per_seat',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='bhintunaticket',
            name='total_price',
        ),
    ]
