# Generated by Django 5.0.7 on 2025-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0016_rename_price_per_seat_bhintunaticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhintunaticket',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registrationdetail',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
