# Generated by Django 5.0.7 on 2025-03-31 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0017_bhintunaticket_seats_registrationdetail_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='IhiLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('event_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ihi_locations', to='adminwork.eventdetail')),
            ],
            options={
                'db_table': 'IhiLocation',
            },
        ),
        migrations.CreateModel(
            name='IhiRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('event_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminwork.eventregistration')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminwork.ihilocation')),
            ],
            options={
                'db_table': 'IhiRegistration',
            },
        ),
    ]
