# Generated by Django 5.0.7 on 2025-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminwork', '0019_eventregistration_check_in_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='formatted_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
